config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register', edit: 'settings' }

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'application#home'

  get '/home', to: 'application#home', as: 'home'
  get '/secret', to: 'application#secret', as: 'secret'
  get '/about', to: 'application#about', as: 'about'
  get '/contact', to: 'application#contact', as: 'contact'

  # by hanson
  get '/chats', to: 'application#chats', as: 'chats'
  post '/chats', to: 'application#chatform', as: 'new_chat'
  get '/chatform', to: 'application#chatform', as: 'chatform'
  post '/chatform', to: 'application#chatform', as: 'sendchat'
  delete '/chats/:id', to: 'application#delete_chat', as: 'delete_chat'
  get '/chatform/:id', to: 'application#edit_chat', as: 'chat'
  patch '/chatform/:id', to: 'application#update_chat', as: 'update_chat'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  validates_presence_of :chat
  validates_presence_of :sender_id
  validates_presence_of :receiver_id

  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :receiver, class_name: 'User', foreign_key: 'receiver_id'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  enum role: [:user, :trainer, :admin]

  def name
    "#{first_name} #{last_name}"
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:home, :about, :contact]
  before_action :only_admin, only: [:delete_chat, :edit_chat, :update_chat]
  def home
  end

  def about
  end

  def contact
  end

  def secret
  end

  # by hanson
  def chats
    if current_user.admin?
      @chats = Chat.all
    else
      @chats = Chat.where([ "sender_id = ? or receiver_id = ?", current_user.id, current_user.id ])
    end
  end

  # by hanson
  def chatform
    if params[:chat].present?
      @chat = Chat.create({
        sender_id: current_user.id,
        receiver_id: params[:chat][:receiver_id],
        chat: params[:chat][:chat]
      })
    else
      @chat = Chat.new
    end

    @users = User.where.not(role: :admin)
  end

  # by hanson
  def delete_chat
    @chat = Chat.find(params[:id])
    @chat.destroy if @chat.present?
    redirect_back fallback_location: '/'
  end

  # by hanson
  def edit_chat
    @chat = Chat.find(params[:id])
    @users = User.where.not(role: :admin)
    render 'chatform'
  end

  # by hanson
  def update_chat
    @chat = Chat.find(params[:id])
    @chat.update(params.require('chat').permit(:receiver_id, :chat));
    @users = User.where.not(role: :admin)
    render 'chatform'
  end

  protected

  def only_admin
    render 'not_auth', :status => :unauthorized unless current_user.admin?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devise_helper.rb
module DeviseHelper
  # A simple way to show error messages for the current devise resource. If you need
  # to customize this method, you can either overwrite it in your application helpers or
  # copy the views to your application.
  #
  # This method is intended to stay simple and it is unlikely that we are going to change
  # it to add more behavior or options.
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      count: resource.errors.count,
                      resource: resource.class.model_name.human.downcase)

    html = <<-HTML
    <p>#{sentence}</p>
    <ul>#{messages}</ul>
    HTML

    html.html_safe
  end
end

app/views/application/about.html.slim
= content_for :title do
  = 'About'

.text-center
  h1 About
  p.text-success about details goes here

app/views/application/chatform.html.erb
<% content_for(:title) do %>
  Send Chat
<% end %>

<%= form_for @chat, html: {class: "form-horizontal center"} do |f| %>
  <% if @chat.errors.full_messages.any? %>
    <% @chat.errors.full_messages.each do |error_message| %>
      <%= error_message %>
    <% end %>
  <% end %>

  <div class="form-group">
    <%= f.label :receiver_id, "Receiver:", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.select(:receiver_id, options_for_select(@users.map{|u| [u.name, u.id]}, f.object.receiver_id), {include_blank: true}, {class: "form-control"}) %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :chat, "Message:", class: "col-md-4 control-label" %>
    <div class="col-md-8">
      <%= f.text_field :chat, class: "form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-md-offset-4 col-md-8">
      <%= f.submit "Submit", class: "btn btn-default btn-primary" %>
    </div>
  </div>
<% end %>

app/views/application/chats.html.erb
<% content_for(:title) do %>
  Chats
<% end %>
<div class="container-fluid">
  <% if @chats.length === 0 %>
    <div class="alert alert-danger">Nothing to show...</div>
  <% end %>

  <% unless current_user.admin? %>
    <% @chats.each do |chat| %>
      <% if chat.sender_id === current_user.id %>
        <div class="alert alert-success">To: <%= chat.receiver.name %> - <%= chat.chat %> (<%= distance_of_time_in_words_to_now(chat.created_at) %> ago)</div>
      <% else %>
        <div class="alert alert-warning text-right">From: <%= chat.sender.name %> - <%= chat.chat %> (<%= distance_of_time_in_words_to_now(chat.created_at) %> ago)</div>
      <% end %>
    <% end %>
  <% else %>
    <% @chats.each do |chat| %>
      <div class="alert alert-success">From: <%= chat.sender.name %>, To: <%= chat.receiver.name %> - <%= chat.chat %> (<%= distance_of_time_in_words_to_now(chat.created_at) %> ago)

        <div class="actions">
          <%= link_to "Edit".html_safe, chat_path(id: chat.id) %>
          <%= link_to "Delete".html_safe, delete_chat_path(id: chat.id), data: {method: 'DELETE'} %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/application/contact.html.slim
= content_for :title do
  = 'Contact'

.text-center
  h1 Contact
  p.text-success contact details goes here

app/views/application/home.html.slim
.text-center
  h1 Home
  p.text-success this is a landing page
  p.text-success bootstrap, devise(login, register, settings, sign out), lato-font and slim is configured!

app/views/application/not_auth.html.slim
= content_for :title do
  = 'Not Authorized'

.text-center
  h1 You are not authorized to access this page

app/views/application/secret.html.slim
= content_for :title do
  = 'Secret'

.text-center
  h1 Secret
  p.text-success only logged in user can access this page

app/views/layouts/_navigation.html.slim
ul class="nav navbar-nav"
  li= link_to('<span class="glyphicon glyphicon-home"></span> Home'.html_safe, root_path)
  - if current_user
    li= link_to('<span class="glyphicon glyphicon-envelope"></span> Chats'.html_safe, chats_path)
    li= link_to('<span class="glyphicon glyphicon-bullhorn"></span> Send Message'.html_safe, chatform_path)
  - else
    li= link_to('<span class="glyphicon glyphicon-phone-alt"></span> Contact'.html_safe, contact_path)
    li= link_to('<span class="glyphicon glyphicon-user"></span> About'.html_safe, about_path)

ul class="nav navbar-nav navbar-right"
  - if current_user
    li= link_to('<span class="glyphicon glyphicon-cog"></span> Settings'.html_safe, edit_user_registration_path)
    li= link_to('<span class="glyphicon glyphicon-off"></span> Log out'.html_safe, destroy_user_session_path, method: 'delete')
  - else
    li= link_to('<span class="glyphicon glyphicon-log-in"></span> Login'.html_safe, new_user_session_path)
    li= link_to('<span class="glyphicon glyphicon-saved"></span> Register'.html_safe, new_user_registration_path)

app/views/layouts/_notifications.html.slim
- if notice
  .alert.alert-info
    p= notice

- if alert
  .alert.alert-warning
    p= alert

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
	  <title><%= content_for?(:title) ? yield(:title) + " - #{APPLICATION_NAME}" : "#{APPLICATION_NAME}" %></title>
	  <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	  <%= csrf_meta_tags %>

  </head>

  <body>
	  <nav class="navbar navbar-default">
		  <div class="container-fluid">
			  <div class="navbar-header">
				  <button type="button" class="navbar-toggle collapsed"
				          data-toggle="collapse" data-target="#menu-collapse">
					  <span class="sr-only">Toggle navigation</span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
					  <span class="icon-bar"></span>
				  </button>
				  <%= link_to APPLICATION_NAME, root_path, class: 'navbar-brand' %>
			  </div>

			  <div class="collapse navbar-collapse" id="menu-collapse">

				  <%= render 'layouts/navigation' %>

			  </div>
		  </div>
	  </nav>

	  <div class="container">
		  <%= render 'layouts/notifications' %>

      <%= yield %>
	  </div>
  </body>
</html>